version: "3.1"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: secret
